### ISSUE TITLE
BlockScout 正式部署疑问

### ISSUE THREAD

**Issue by tinyhill666** [holechain/holechain.github.io#3]
我在云服务器跑，indexer在工作了，但是网页访问一直搞不定，请问你有试过正式部署吗

**Comment by mhxw** [comment]
不好意思，现在才看到你的消息。如果你仍然感兴趣，可以参考 Blockscout 的文档进行部署。文档内容已经非常详细，而且代码也发生了不少变更，建议根据最新版本的文档操作哈。
